import { prisma, TenantPrismaClient } from "../../config/database";
import { NotFoundError } from "../../shared/errors/NotFoundError";
import { ValidationError } from "../../shared/errors/ValidationError";
import { getNextNumber } from "../../shared/utils/invoiceNumber";
import { logger } from "../../shared/utils/logger";
import { applyStockDelta } from "../inventory/stockUpsert";
import { getLowStockItems } from "../inventory/inventory.service";
import { getPreferredVendor } from "../product/product-supplier.service";
import type {
  CreatePurchaseInput,
  ReceiveGoodsInput,
  AddPaymentInput,
  ListPurchasesInput,
} from "./purchase.validation";
import { assertVariableProductHasVariant } from "../product/product.validation";

// ── List POs ────────────────────────────────────────────────────────────────────

export async function listPurchases(db: TenantPrismaClient, filters: ListPurchasesInput) {
  const where: Record<string, unknown> = {};

  if (filters.supplierId) where.supplierId = filters.supplierId;
  if (filters.storeId) where.storeId = filters.storeId;
  if (filters.status) where.status = filters.status;

  if (filters.dateFrom || filters.dateTo) {
    where.createdAt = {
      ...(filters.dateFrom && { gte: filters.dateFrom }),
      ...(filters.dateTo && { lte: filters.dateTo }),
    };
  }

  const skip = (filters.page - 1) * filters.limit;

  const [data, total] = await Promise.all([
    db.purchaseOrder.findMany({
      where,
      include: {
        supplier: { select: { id: true, name: true } },
        store: { select: { id: true, name: true, code: true } },
        _count: { select: { items: true } },
      },
      orderBy: { [filters.sortBy]: filters.sortOrder },
      skip,
      take: filters.limit,
    }),
    db.purchaseOrder.count({ where }),
  ]);

  return {
    data,
    pagination: {
      page: filters.page,
      limit: filters.limit,
      total,
      totalPages: Math.ceil(total / filters.limit),
      hasMore: filters.page * filters.limit < total,
    },
  };
}

// ── Get PO by ID ────────────────────────────────────────────────────────────────

export async function getPurchaseById(db: TenantPrismaClient, purchaseId: string) {
  const po = await db.purchaseOrder.findUnique({
    where: { id: purchaseId },
    include: {
      supplier: true,
      store: { select: { id: true, name: true, code: true } },
      items: {
        include: {
          product: { select: { id: true, name: true, sku: true } },
          variant: { select: { id: true, name: true, sku: true } },
        },
      },
    },
  });
  if (!po) throw new NotFoundError("Purchase Order", purchaseId);
  return po;
}

// ── Create PO ───────────────────────────────────────────────────────────────────

export interface CreatePurchaseOpts {
  /** Marks the PO as drafted by the 3H.2 auto-reorder trigger (dedupe + reporting). */
  autoGenerated?: boolean;
  /** Override the initial status (default "ORDERED"); the auto-reorder path uses "DRAFT". */
  status?: "DRAFT" | "ORDERED";
}

export async function createPurchase(
  db: TenantPrismaClient,
  tenantId: string,
  input: CreatePurchaseInput,
  opts: CreatePurchaseOpts = {},
) {
  const supplier = await db.supplier.findUnique({
    where: { id: input.supplierId },
  });
  if (!supplier) throw new NotFoundError("Supplier", input.supplierId);

  const store = await db.store.findUnique({ where: { id: input.storeId } });
  if (!store) throw new NotFoundError("Store", input.storeId);

  const subtotal = input.items.reduce((sum, i) => sum + i.unitCost * i.orderedQty, 0);
  const grandTotal = subtotal + input.shippingCost;

  const productIds = [...new Set(input.items.map((i) => i.productId))];
  const products = await db.product.findMany({
    where: { id: { in: productIds } },
    select: { id: true, productType: true, name: true },
  });
  const productById = new Map(products.map((p) => [p.id, p]));
  for (const line of input.items) {
    const p = productById.get(line.productId);
    if (!p) throw new NotFoundError("Product", line.productId);
    assertVariableProductHasVariant(
      p.productType,
      line.variantId,
      `Purchase line for "${p.name}" requires variantId because this product is variable.`,
    );
  }

  return prisma.$transaction(async (tx) => {
    const purchaseNo = await getNextNumber(tx as never, tenantId, "purchase", "PO-");

    const po = await tx.purchaseOrder.create({
      data: {
        tenantId,
        supplierId: input.supplierId,
        storeId: input.storeId,
        purchaseNo,
        status: opts.status ?? "ORDERED",
        subtotal,
        taxTotal: 0,
        shippingCost: input.shippingCost,
        grandTotal,
        paidAmount: 0,
        expectedDate: input.expectedDate ?? null,
        notes: input.notes ?? null,
        autoGenerated: opts.autoGenerated ?? false,
        items: {
          create: input.items.map((i) => ({
            productId: i.productId,
            variantId: i.variantId ?? null,
            orderedQty: i.orderedQty,
            receivedQty: 0,
            unitCost: i.unitCost,
            lineTotal: i.unitCost * i.orderedQty,
          })),
        },
      },
      include: {
        items: true,
        supplier: { select: { id: true, name: true } },
      },
    });

    logger.info({ tenantId, purchaseId: po.id, purchaseNo }, "Purchase order created");
    return po;
  });
}

// ── Reorder suggestions (3H.2) ──────────────────────────────────────────────────
// Products at/below their low-stock threshold for a store, joined to their
// preferred vendor + a suggested order qty. Single source of truth for the
// manual "draft these" view — mirrors exactly what the auto-reorder trigger does.
export async function getReorderSuggestions(db: TenantPrismaClient, storeId?: string) {
  const low = await getLowStockItems(db, { page: 1, limit: 500, storeId } as never);
  const suggestions = await Promise.all(
    low.data.map(async (row: any) => {
      const vendor = await getPreferredVendor(db, row.productId);
      const threshold = row.lowStockThreshold ?? 0;
      return {
        productId: row.productId,
        product: row.product,
        storeId: row.storeId,
        currentQty: row.quantity,
        threshold,
        preferredVendor: vendor
          ? { supplierId: vendor.supplierId, costPrice: vendor.costPrice, reorderQty: vendor.reorderQty ?? null }
          : null,
        suggestedQty: vendor?.reorderQty ?? Math.max(threshold, 1),
      };
    }),
  );
  return suggestions;
}

// ── Receive goods ───────────────────────────────────────────────────────────────

export async function receiveGoods(
  _db: TenantPrismaClient,
  tenantId: string,
  purchaseId: string,
  userId: string,
  input: ReceiveGoodsInput,
) {
  return prisma.$transaction(
    async (tx) => {
      const po = await tx.purchaseOrder.findFirst({
        where: { id: purchaseId, tenantId },
        include: { items: true },
      });

      if (!po) throw new NotFoundError("Purchase Order", purchaseId);
      if (po.status === "CANCELLED") throw new ValidationError("Cannot receive on cancelled PO");
      if (po.status === "RECEIVED") throw new ValidationError("PO already fully received");

      const poItemMap = new Map(po.items.map((i) => [i.id, i]));

      for (const item of input.items) {
        const poItem = poItemMap.get(item.purchaseItemId);
        if (!poItem) throw new NotFoundError("Purchase Item", item.purchaseItemId);

        const remaining = poItem.orderedQty - poItem.receivedQty;
        if (item.receivedQty > remaining) {
          throw new ValidationError(
            `Cannot receive ${item.receivedQty} — only ${remaining} remaining`,
          );
        }

        // Update PO item
        await tx.purchaseItem.update({
          where: { id: item.purchaseItemId },
          data: { receivedQty: { increment: item.receivedQty } },
        });

        // Race-safe stock increment via atomic INSERT ... ON CONFLICT.
        // Handles both "row exists" and "row doesn't exist yet" atomically,
        // and prevents duplicate StoreStock rows under concurrent receives.
        const afterQty = await applyStockDelta(
          tx as never,
          po.storeId,
          poItem.productId,
          poItem.variantId,
          item.receivedQty,
        );

        await tx.stockMovement.create({
          data: {
            tenantId,
            storeId: po.storeId,
            productId: poItem.productId,
            variantId: poItem.variantId,
            type: "PURCHASE_IN",
            quantityChange: item.receivedQty,
            quantityAfter: afterQty,
            referenceId: purchaseId,
            referenceType: "PURCHASE",
            performedBy: userId,
          },
        });
      }

      // Update PO status
      const updatedItems = await tx.purchaseItem.findMany({
        where: { purchaseId },
      });
      const allReceived = updatedItems.every((i) => i.receivedQty >= i.orderedQty);
      const someReceived = updatedItems.some((i) => i.receivedQty > 0);
      const newStatus = allReceived ? "RECEIVED" : someReceived ? "PARTIAL" : po.status;

      await tx.purchaseOrder.update({
        where: { id: purchaseId },
        data: { status: newStatus },
      });

      logger.info({ tenantId, purchaseId, status: newStatus }, "Goods received");
      return { success: true, status: newStatus };
    },
    { timeout: 30000 },
  );
}

// ── Add payment to PO ───────────────────────────────────────────────────────────

export async function addPayment(
  db: TenantPrismaClient,
  tenantId: string,
  purchaseId: string,
  input: AddPaymentInput,
) {
  const po = await db.purchaseOrder.findUnique({ where: { id: purchaseId } });
  if (!po) throw new NotFoundError("Purchase Order", purchaseId);

  const currentPaid = Number(po.paidAmount);
  const grandTotal = Number(po.grandTotal);
  const remaining = grandTotal - currentPaid;

  if (input.amount > remaining) {
    throw new ValidationError(`Payment (${input.amount}) exceeds remaining balance (${remaining})`);
  }

  const newPaid = currentPaid + input.amount;

  await db.purchaseOrder.update({
    where: { id: purchaseId },
    data: { paidAmount: newPaid },
  });

  // Update supplier balance
  await db.supplier.update({
    where: { id: po.supplierId },
    data: { balance: { decrement: input.amount } },
  });

  logger.info({ tenantId, purchaseId, amount: input.amount }, "PO payment added");
  return { paidAmount: newPaid, remaining: grandTotal - newPaid };
}

// ── Cancel PO ───────────────────────────────────────────────────────────────────

export async function cancelPurchase(db: TenantPrismaClient, purchaseId: string) {
  const po = await db.purchaseOrder.findUnique({ where: { id: purchaseId } });
  if (!po) throw new NotFoundError("Purchase Order", purchaseId);
  if (po.status === "RECEIVED") throw new ValidationError("Cannot cancel a fully received PO");

  const updated = await db.purchaseOrder.update({
    where: { id: purchaseId },
    data: { status: "CANCELLED" },
  });

  logger.info({ purchaseId }, "Purchase order cancelled");
  return updated;
}
