// 3H.2 auto-reorder trigger. Runs BEST-EFFORT after the checkout transaction
// commits (see checkout.service). Redis-free — no BullMQ (the orphaned
// lowStockQueue is Redis-backed and dead on the store-node). For each affected
// line that fell to/below its low-stock threshold:
//   • always raise the in-app low-stock alert (finally firing the orphaned path);
//   • if a preferred vendor exists AND the tenant enabled auto-reorder, draft a
//     DRAFT autoGenerated PO at the reorder qty (deduped against an existing open
//     auto PO for the same product+vendor);
//   • if auto-email is on (per-vendor override ?? tenant toggle), email the PO to
//     the vendor via the 3H.1 messaging outbox.
// NEVER throws into the caller — a reorder problem must not break/slow a sale.

import { getPreferredVendor } from "../product/product-supplier.service";
import { createPurchase } from "../purchase/purchase.service";
import { enqueue, loadTenantContext } from "../messaging/messaging.service";
import { renderPurchaseOrderHtml } from "../purchase/purchase-order.render";
import { readReorderSettings } from "../../shared/settings";
import { notifyLowStock } from "./reorder.notify";
import { logger } from "../../shared/utils/logger";

export interface AffectedLine {
  productId: string;
  variantId?: string | null;
  newQty: number;
}

// Open PO statuses that count for dedupe (an in-flight auto order already covers it).
const OPEN_PO_STATUSES = ["DRAFT", "ORDERED", "PARTIAL"] as const;

export async function maybeReorder(
  db: any,
  ctx: { tenantId: string; storeId: string },
  affected: AffectedLine[],
): Promise<void> {
  try {
    if (!affected.length) return;
    const tenant = await db.tenant.findUnique({
      where: { id: ctx.tenantId },
      select: { id: true, encryptionKeyVersion: true, settings: true },
    });
    const reorder = readReorderSettings(tenant ?? { settings: {} });

    for (const line of affected) {
      try {
        const stock = await db.storeStock.findFirst({
          where: { storeId: ctx.storeId, productId: line.productId, variantId: line.variantId ?? null },
        });
        const threshold = stock?.lowStockThreshold ?? 0;
        if (!stock || line.newQty > threshold) continue;

        const product = await db.product.findUnique({
          where: { id: line.productId },
          select: { id: true, name: true },
        });
        const vendor = await getPreferredVendor(db, line.productId);

        // Always surface the in-app alert (Redis-free).
        await notifyLowStock({
          tenantId: ctx.tenantId,
          storeId: ctx.storeId,
          productId: line.productId,
          productName: product?.name ?? line.productId,
          currentQuantity: line.newQty,
          reorderPoint: threshold,
        }).catch(() => {});

        if (!vendor || !reorder.autoReorderEnabled) continue;

        // Dedupe: an open auto PO already covering this product+vendor?
        const existing = await db.purchaseOrder.findFirst({
          where: {
            supplierId: vendor.supplierId,
            autoGenerated: true,
            status: { in: OPEN_PO_STATUSES as unknown as string[] },
            items: { some: { productId: line.productId } },
          },
          select: { id: true },
        });
        if (existing) continue;

        const qty = (vendor.reorderQty as number | null | undefined) ?? Math.max(threshold, 1);
        const po = await createPurchase(
          db,
          ctx.tenantId,
          {
            supplierId: vendor.supplierId as string,
            storeId: ctx.storeId,
            shippingCost: 0,
            items: [
              {
                productId: line.productId,
                variantId: line.variantId ?? null,
                orderedQty: qty,
                unitCost: Number(vendor.costPrice),
              },
            ],
          },
          { autoGenerated: true, status: "DRAFT" },
        );

        const autoEmail = vendor.autoEmail ?? reorder.autoEmailReorder;
        if (autoEmail) {
          const supplier = await db.supplier.findUnique({
            where: { id: vendor.supplierId },
            select: { name: true, email: true },
          });
          if (supplier?.email) {
            const full = await db.purchaseOrder.findUnique({
              where: { id: po.id },
              include: {
                supplier: true,
                items: { include: { product: { select: { name: true } } } },
              },
            });
            const tctx = await loadTenantContext(db, ctx.tenantId);
            await enqueue(db, tctx, {
              tenantId: ctx.tenantId,
              storeId: ctx.storeId,
              kind: "PURCHASE_ORDER",
              to: { email: supplier.email, name: supplier.name },
              subject: `Purchase Order ${po.purchaseNo}`,
              html: renderPurchaseOrderHtml(full),
              related: { type: "PurchaseOrder", id: po.id },
            }).catch(() => {});
          }
        }
      } catch (err) {
        logger.error({ err, productId: line.productId }, "maybeReorder: line failed");
      }
    }
  } catch (err) {
    logger.error({ err }, "maybeReorder failed");
  }
}
