import { z } from "zod";
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<{
        development: "development";
        production: "production";
        test: "test";
    }>>;
    PORT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    DATABASE_URL: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    DATA_BACKEND: z.ZodDefault<z.ZodEnum<{
        postgres: "postgres";
        sqlite: "sqlite";
    }>>;
    SQLITE_DATABASE_URL: z.ZodDefault<z.ZodString>;
    JWT_ACCESS_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_ACCESS_EXPIRY: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRY: z.ZodDefault<z.ZodString>;
    JWT_ACCESS_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    JWT_REFRESH_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    BCRYPT_ROUNDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    MASTER_ENCRYPTION_KEY: z.ZodOptional<z.ZodString>;
    LOCAL_DB_PATH: z.ZodDefault<z.ZodString>;
    LOCAL_DB_MASTER_KEY: z.ZodOptional<z.ZodString>;
    SYNC_DEVICE_ID: z.ZodDefault<z.ZodString>;
    SYNC_TOKEN_SECRET: z.ZodString;
    SYNC_TOKEN_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    CLOUD_SYNC_URL: z.ZodDefault<z.ZodString>;
    SYNC_CLOUD_URL: z.ZodOptional<z.ZodString>;
    LICENSE_TOKEN_SECRET: z.ZodString;
    LICENSE_TOKEN_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    LICENSE_KEY: z.ZodOptional<z.ZodString>;
    CLOUD_LICENSE_URL: z.ZodDefault<z.ZodString>;
    LICENSE_DEGRADE_DAYS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    LICENSE_LOCKOUT_DAYS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    DEVICE_FINGERPRINT: z.ZodOptional<z.ZodString>;
    PIN_PEPPER_SECRET: z.ZodString;
    PIN_PEPPER_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    POS_OVERRIDE_SECRET: z.ZodString;
    POS_OVERRIDE_SECRET_PREVIOUS: z.ZodOptional<z.ZodString>;
    PIN_MAX_ATTEMPTS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    PIN_LOCKOUT_MINUTES: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SENDGRID_API_KEY: z.ZodOptional<z.ZodString>;
    SENDGRID_FROM_EMAIL: z.ZodOptional<z.ZodString>;
    DEMO_MODE: z.ZodPipe<z.ZodDefault<z.ZodString>, z.ZodTransform<boolean, string>>;
}, z.core.$strip>;
export declare const config: {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    REDIS_URL: string;
    DATA_BACKEND: "postgres" | "sqlite";
    SQLITE_DATABASE_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_ACCESS_EXPIRY: string;
    JWT_REFRESH_EXPIRY: string;
    BCRYPT_ROUNDS: number;
    RATE_LIMIT_MAX: number;
    RATE_LIMIT_WINDOW_MS: number;
    CORS_ORIGINS: string;
    LOCAL_DB_PATH: string;
    SYNC_DEVICE_ID: string;
    SYNC_TOKEN_SECRET: string;
    CLOUD_SYNC_URL: string;
    LICENSE_TOKEN_SECRET: string;
    CLOUD_LICENSE_URL: string;
    LICENSE_DEGRADE_DAYS: number;
    LICENSE_LOCKOUT_DAYS: number;
    PIN_PEPPER_SECRET: string;
    POS_OVERRIDE_SECRET: string;
    PIN_MAX_ATTEMPTS: number;
    PIN_LOCKOUT_MINUTES: number;
    DEMO_MODE: boolean;
    DATABASE_URL?: string | undefined;
    JWT_ACCESS_SECRET_PREVIOUS?: string | undefined;
    JWT_REFRESH_SECRET_PREVIOUS?: string | undefined;
    MASTER_ENCRYPTION_KEY?: string | undefined;
    LOCAL_DB_MASTER_KEY?: string | undefined;
    SYNC_TOKEN_SECRET_PREVIOUS?: string | undefined;
    SYNC_CLOUD_URL?: string | undefined;
    LICENSE_TOKEN_SECRET_PREVIOUS?: string | undefined;
    LICENSE_KEY?: string | undefined;
    DEVICE_FINGERPRINT?: string | undefined;
    PIN_PEPPER_SECRET_PREVIOUS?: string | undefined;
    POS_OVERRIDE_SECRET_PREVIOUS?: string | undefined;
    SENDGRID_API_KEY?: string | undefined;
    SENDGRID_FROM_EMAIL?: string | undefined;
};
export type Config = z.infer<typeof envSchema>;
export {};
//# sourceMappingURL=index.d.ts.map