// scripts/generate-sync-triggers.ts
// ─────────────────────────────────────────────────────────────────────────────
// CLI entrypoint for the store-node sync-outbox capture-trigger generator
// (SN-3 Task 1). The actual pure logic (`buildSyncTriggers`, `deriveSyncTables`)
// lives in `src/local/sync-triggers.ts` — see that file's header for why: it
// needs to be importable from `src/local/sqlite-push.ts` (which installs the
// generated triggers on the live encrypted DB at push time), and a `src/**`
// file cannot import from `scripts/**` without tripping the tsc `rootDir`
// check (scripts/ is intentionally excluded from the compiled project, run
// only via `tsx`). Re-exported here so this module keeps the exact import
// surface `scripts/__tests__/generate-sync-triggers.test.ts` expects
// (`import { buildSyncTriggers } from "../generate-sync-triggers"`), and so
// `main()` below can print the DDL for the real schema to stdout.
// ─────────────────────────────────────────────────────────────────────────────
import fs from "fs";
import path from "path";
import { buildSyncTriggers, deriveSyncTables, type SyncTable } from "../src/local/sync-triggers";

export { buildSyncTriggers, deriveSyncTables, type SyncTable };

function main(): void {
  const schemaPath = path.join(__dirname, "..", "prisma", "schema.sqlite.prisma");
  const schemaSource = fs.readFileSync(schemaPath, "utf8");
  const tables = deriveSyncTables(schemaSource);
  const ddl = buildSyncTriggers(tables);

  // eslint-disable-next-line no-console
  console.log(
    `-- Generated by scripts/generate-sync-triggers.ts — ${tables.length} syncable tables, ${tables.length * 3} triggers.\n`,
  );
  // eslint-disable-next-line no-console
  console.log(ddl);
}

if (require.main === module) {
  main();
}
