export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  SETUP: "/setup",
  DASHBOARD: "/dashboard",
  MANAGER_DASHBOARD: "/manager-dashboard",
  POS: "/pos",
  PRODUCTS: "/products",
  CATEGORIES: "/categories",
  BRANDS: "/brands",
  LEVIES: "/levies",
  INVENTORY: "/inventory",
  SALES: "/sales",
  CUSTOMERS: "/customers",
  SUPPLIERS: "/suppliers",
  PURCHASES: "/purchases",
  EXPENSES: "/expenses",
  REPORTS: "/reports",
  REPORTS_HR: "/reports/hr",
  USERS: "/users",
  USERS_PERMISSIONS: "/permissions",
  STORES: "/stores",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  RECEIPT_SETTINGS: "/receipt-settings",
  // HR (v2)
  HR_EMPLOYEES: "/hr/employees",
  HR_EMPLOYEES_NEW: "/hr/employees/new",
  HR_DEPARTMENTS: "/hr/departments",
  HR_DESIGNATIONS: "/hr/designations",
  HR_ATTENDANCE: "/hr/attendance",
  HR_ATTENDANCE_CORRECTIONS: "/hr/attendance/corrections",
  HR_ATTENDANCE_CORRECTIONS_NEW: "/hr/attendance/corrections/new",
  HR_SHIFTS: "/hr/shifts",
  HR_SHIFTS_NEW: "/hr/shifts/new",
  HR_SHIFTS_SCHEDULE: "/hr/shifts/schedule",
  HR_SHIFTS_SCHEDULE_NEW: "/hr/shifts/schedule/new",
  HR_SHIFTS_SWAPS: "/hr/shifts/swaps",
  HR_SHIFTS_SWAPS_NEW: "/hr/shifts/swaps/new",
  // HR Leave & Holidays
  HR_LEAVE: "/hr/leave",
  HR_LEAVE_POLICIES: "/hr/leave/policies",
  HR_LEAVE_REQUESTS: "/hr/leave/requests",
  HR_LEAVE_BALANCES: "/hr/leave/balances",
  HR_HOLIDAYS: "/hr/holidays",
  HR_HOLIDAYS_CALENDAR: "/hr/holidays/calendar",
  // HR Payroll
  HR_PAYROLL: "/hr/payroll",
  HR_PAYROLL_STRUCTURES: "/hr/payroll/structures",
  HR_PAYROLL_SALARIES: "/hr/payroll/salaries",
  HR_PAYROLL_RUNS: "/hr/payroll/runs",
  HR_PAYROLL_ADVANCES: "/hr/payroll/advances",
  // Super Admin
  ADMIN_TENANTS: "/admin/tenants",
  // ESS — Employee Self-Service sub-app at /me/*
  ESS_HOME: "/me",
  ESS_PROFILE: "/me/profile",
  ESS_ATTENDANCE: "/me/attendance",
  ESS_SHIFTS: "/me/shifts",
  ESS_LEAVE: "/me/leave",
  ESS_LEAVE_APPLY: "/me/leave/apply",
  ESS_PAYSLIPS: "/me/payslips",
  ESS_HOLIDAYS: "/me/holidays",
  ESS_DOCUMENTS: "/me/documents",
} as const;
