import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../product/product-supplier.service", () => ({ getPreferredVendor: vi.fn() }));
vi.mock("../../purchase/purchase.service", () => ({
  createPurchase: vi.fn(async () => ({ id: "po1", purchaseNo: "PO-1" })),
}));
vi.mock("../../messaging/messaging.service", () => ({
  enqueue: vi.fn(async () => ({ id: "m1" })),
  loadTenantContext: vi.fn(async () => ({ id: "t1", encryptionKeyVersion: 1, settings: {} })),
}));
vi.mock("../../purchase/purchase-order.render", () => ({ renderPurchaseOrderHtml: () => "<html/>" }));
vi.mock("../reorder.notify", () => ({ notifyLowStock: vi.fn(async () => {}) }));

import { maybeReorder } from "../reorder.service";
import { getPreferredVendor } from "../../product/product-supplier.service";
import { createPurchase } from "../../purchase/purchase.service";
import { enqueue } from "../../messaging/messaging.service";
import { notifyLowStock } from "../reorder.notify";

function makeDb(over: any = {}) {
  return {
    storeStock: { findFirst: vi.fn(async () => ({ quantity: 2, lowStockThreshold: 5 })) },
    product: { findUnique: vi.fn(async () => ({ id: "p1", name: "Aspirin" })) },
    purchaseOrder: { findFirst: vi.fn(async () => null), findUnique: vi.fn(async () => ({ id: "po1", supplier: {}, items: [] })) },
    tenant: {
      findUnique: vi.fn(async () => ({
        id: "t1",
        encryptionKeyVersion: 1,
        settings: { reorder: { autoReorderEnabled: true, autoEmailReorder: false } },
      })),
    },
    supplier: { findUnique: vi.fn(async () => ({ id: "s1", name: "Acme", email: "a@c.co" })) },
    ...over,
  } as any;
}

beforeEach(() => vi.clearAllMocks());

it("drafts a DRAFT autoGenerated PO for the preferred vendor when enabled", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10 });
  await maybeReorder(makeDb(), { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(createPurchase).toHaveBeenCalledWith(
    expect.anything(),
    "t1",
    expect.objectContaining({
      supplierId: "s1",
      storeId: "st1",
      items: [expect.objectContaining({ productId: "p1", orderedQty: 10, unitCost: 2 })],
    }),
    expect.objectContaining({ autoGenerated: true }),
  );
  expect(notifyLowStock).toHaveBeenCalled();
  expect(enqueue).not.toHaveBeenCalled(); // auto-email off
});

it("uses reorderQty fallback (max(threshold,1)) when the vendor has none", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2 });
  await maybeReorder(makeDb(), { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 0 }]);
  expect(createPurchase).toHaveBeenCalledWith(
    expect.anything(),
    "t1",
    expect.objectContaining({ items: [expect.objectContaining({ orderedQty: 5 })] }),
    expect.anything(),
  );
});

it("does nothing (beyond alert) when autoReorderEnabled is false", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2 });
  const db = makeDb({
    tenant: { findUnique: vi.fn(async () => ({ id: "t1", encryptionKeyVersion: 1, settings: { reorder: { autoReorderEnabled: false } } })) },
  });
  await maybeReorder(db, { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(createPurchase).not.toHaveBeenCalled();
  expect(notifyLowStock).toHaveBeenCalled();
});

it("does not reorder when stock is above threshold", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10 });
  const db = makeDb({ storeStock: { findFirst: vi.fn(async () => ({ quantity: 9, lowStockThreshold: 5 })) } });
  await maybeReorder(db, { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 9 }]);
  expect(createPurchase).not.toHaveBeenCalled();
  expect(notifyLowStock).not.toHaveBeenCalled();
});

it("dedupes: no second PO when an open auto PO already covers the product+vendor", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10 });
  const db = makeDb({ purchaseOrder: { findFirst: vi.fn(async () => ({ id: "existing" })), findUnique: vi.fn() } });
  await maybeReorder(db, { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(createPurchase).not.toHaveBeenCalled();
});

it("emails the vendor when auto-email is on (tenant toggle)", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10, autoEmail: null });
  const db = makeDb({
    tenant: { findUnique: vi.fn(async () => ({ id: "t1", encryptionKeyVersion: 1, settings: { reorder: { autoReorderEnabled: true, autoEmailReorder: true } } })) },
  });
  await maybeReorder(db, { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(enqueue).toHaveBeenCalledWith(
    expect.anything(),
    expect.anything(),
    expect.objectContaining({ kind: "PURCHASE_ORDER", to: { email: "a@c.co", name: "Acme" } }),
  );
});

it("per-vendor autoEmail=false overrides tenant auto-email on", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10, autoEmail: false });
  const db = makeDb({
    tenant: { findUnique: vi.fn(async () => ({ id: "t1", encryptionKeyVersion: 1, settings: { reorder: { autoReorderEnabled: true, autoEmailReorder: true } } })) },
  });
  await maybeReorder(db, { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(enqueue).not.toHaveBeenCalled();
});

it("raises only the in-app alert when there is no preferred vendor", async () => {
  (getPreferredVendor as any).mockResolvedValue(null);
  await maybeReorder(makeDb(), { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]);
  expect(notifyLowStock).toHaveBeenCalled();
  expect(createPurchase).not.toHaveBeenCalled();
});

it("never throws even if createPurchase fails", async () => {
  (getPreferredVendor as any).mockResolvedValue({ supplierId: "s1", costPrice: 2, reorderQty: 10 });
  (createPurchase as any).mockRejectedValue(new Error("boom"));
  await expect(
    maybeReorder(makeDb(), { tenantId: "t1", storeId: "st1" }, [{ productId: "p1", newQty: 2 }]),
  ).resolves.toBeUndefined();
});
