import { Role } from "@/types/enums/role.enums";

export const PERMISSIONS = {
  TENANT_MANAGE: "tenant:manage",
  STORE_MANAGE: "store:manage",
  USER_MANAGE: "user:manage",
  USER_MANAGE_STORE: "user:manage_store",
  PRODUCT_READ: "product:read",
  PRODUCT_WRITE: "product:write",
  CATEGORY_READ: "category:read",
  CATEGORY_WRITE: "category:write",
  INVENTORY_READ: "inventory:read",
  INVENTORY_WRITE: "inventory:write",
  SALE_CREATE: "sale:create",
  SALE_READ: "sale:read",
  SALE_READ_OWN: "sale:read_own",
  SALE_VOID: "sale:void",
  SALE_RETURN: "sale:return",
  PURCHASE_READ: "purchase:read",
  PURCHASE_WRITE: "purchase:write",
  PURCHASE_RECEIVE: "purchase:receive",
  CUSTOMER_READ: "customer:read",
  CUSTOMER_WRITE: "customer:write",
  SUPPLIER_READ: "supplier:read",
  SUPPLIER_WRITE: "supplier:write",
  EXPENSE_READ: "expense:read",
  EXPENSE_WRITE: "expense:write",
  REPORT_READ: "report:read",
  REPORT_READ_OWN: "report:read_own",
  REPORT_EXPORT: "report:export",
  SHIFT_MANAGE: "shift:manage",
  SHIFT_OWN: "shift:own",
  SETTINGS_MANAGE: "settings:manage",
  RECEIPT_READ: "receipt:read",
  RECEIPT_WRITE: "receipt:write",
  RECEIPT_GENERATE: "receipt:generate",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(PERMISSIONS), // wildcard semantically
  [Role.ADMIN]: [
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.STORE_MANAGE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.SALE_VOID,
    PERMISSIONS.SALE_RETURN,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_WRITE,
    PERMISSIONS.PURCHASE_RECEIVE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_WRITE,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_WRITE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_WRITE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.RECEIPT_READ,
    PERMISSIONS.RECEIPT_WRITE,
    PERMISSIONS.RECEIPT_GENERATE,
  ],
  [Role.MANAGER]: [
    PERMISSIONS.USER_MANAGE_STORE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_WRITE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.SALE_VOID,
    PERMISSIONS.SALE_RETURN,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_WRITE,
    PERMISSIONS.PURCHASE_RECEIVE,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_WRITE,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.SUPPLIER_WRITE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_WRITE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.SHIFT_MANAGE,
    PERMISSIONS.RECEIPT_READ,
    PERMISSIONS.RECEIPT_GENERATE,
  ],
  [Role.CASHIER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ_OWN,
    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_WRITE,
    PERMISSIONS.SHIFT_OWN,
    PERMISSIONS.REPORT_READ_OWN,
    PERMISSIONS.RECEIPT_GENERATE,
  ],

  [Role.HR_MANAGER]: [
    PERMISSIONS.USER_MANAGE_STORE,
    PERMISSIONS.REPORT_READ,
    // ── v2 strings the backend grants HR_MANAGER ──────────
    "hr.employees.read" as Permission,
    "hr.employees.read.sensitive" as Permission,
    "hr.employees.read.salary" as Permission,
    "hr.employees.create" as Permission,
    "hr.employees.update" as Permission,
    "hr.employees.update.sensitive" as Permission,
    "hr.employees.update.salary" as Permission,
    "hr.employees.terminate" as Permission,
    "hr.employees.documents.read" as Permission,
    "hr.employees.documents.upload" as Permission,
    "hr.employees.documents.delete" as Permission,
    "hr.departments.read" as Permission,
    "hr.departments.manage" as Permission,
    "hr.designations.read" as Permission,
    "hr.designations.manage" as Permission,
    "hr.contracts.read" as Permission,
    "hr.contracts.create" as Permission,
    "hr.attendance.read.team" as Permission,
    "hr.attendance.read.all" as Permission,
    "hr.attendance.regularize.approve" as Permission,
    "hr.shifts.read" as Permission,
    "hr.shifts.template.manage" as Permission,
    "hr.shifts.schedule.read" as Permission,
    "hr.shifts.schedule.create" as Permission,
    "hr.shifts.schedule.update" as Permission,
    "hr.shifts.schedule.delete" as Permission,
    "hr.leave.types.read" as Permission,
    "hr.leave.types.manage" as Permission,
    "hr.leave.policies.read" as Permission,
    "hr.leave.policies.manage" as Permission,
    "hr.leave.balances.read.team" as Permission,
    "hr.leave.balances.read.all" as Permission,
    "hr.leave.balances.adjust" as Permission,
    "hr.leave.request.read.team" as Permission,
    "hr.leave.request.read.all" as Permission,
    "hr.leave.request.approve" as Permission,
    "hr.leave.request.reject" as Permission,
    "hr.holidays.read" as Permission,
    "hr.holidays.manage" as Permission,
    "hr.payroll.read" as Permission,
    "hr.payroll.read.payslip.all" as Permission,
    "hr.payroll.salary-structure.read" as Permission,
    "hr.payroll.salary-structure.manage" as Permission,
    "hr.payroll.run.create" as Permission,
    "hr.payroll.run.process" as Permission,
    "reports.hr.attendance.read" as Permission,
    "reports.hr.payroll.read" as Permission,
    "reports.export" as Permission,
    "users.read" as Permission,
    "users.create" as Permission,
    "users.password.reset" as Permission,
    "stores.read" as Permission,
  ],
  [Role.ACCOUNTANT]: [
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_WRITE,
  ],

  [Role.EMPLOYEE]: [
    "ess.profile.read" as Permission,
    "ess.profile.update" as Permission,
    "ess.attendance.read" as Permission,
    "ess.attendance.check-in" as Permission,
    "ess.attendance.check-out" as Permission,
    "ess.attendance.regularize" as Permission,
    "ess.shifts.read" as Permission,
    "ess.shifts.swap.request" as Permission,
    "ess.shifts.swap.respond" as Permission,
    "ess.leave.types.read" as Permission,
    "ess.leave.balance.read" as Permission,
    "ess.leave.request.create" as Permission,
    "ess.leave.request.read" as Permission,
    "ess.leave.request.cancel" as Permission,
    "ess.payslips.read" as Permission,
    "ess.payslips.download" as Permission,
    "ess.holidays.read" as Permission,
    "ess.documents.read" as Permission,
  ],
};
