export const PERMISSIONS_V2 = {
  // ── Platform (SUPER_ADMIN only) ───────────────────────────────────────
  PLATFORM_TENANTS_READ: "platform.tenants.read",
  PLATFORM_TENANTS_CREATE: "platform.tenants.create",
  PLATFORM_TENANTS_UPDATE: "platform.tenants.update",
  PLATFORM_TENANTS_SUSPEND: "platform.tenants.suspend",
  PLATFORM_TENANTS_DELETE: "platform.tenants.delete",
  PLATFORM_SUBSCRIPTIONS_READ: "platform.subscriptions.read",
  PLATFORM_SUBSCRIPTIONS_UPDATE: "platform.subscriptions.update",
  PLATFORM_USERS_READ: "platform.users.read",
  PLATFORM_USERS_IMPERSONATE: "platform.users.impersonate",
  PLATFORM_AUDIT_READ: "platform.audit.read",
  PLATFORM_ANALYTICS_READ: "platform.analytics.read",
  PLATFORM_AI_USAGE_READ: "platform.ai.usage.read",
  PLATFORM_SYSTEM_MAINTENANCE: "platform.system.maintenance",
  PLATFORM_SYSTEM_BROADCAST: "platform.system.broadcast",

  // ── Tenant settings ────────────────────────────────────────────────────
  TENANT_SETTINGS_READ: "tenant.settings.read",
  TENANT_SETTINGS_UPDATE: "tenant.settings.update",
  TENANT_LOCALE_UPDATE: "tenant.locale.update",
  TENANT_APPEARANCE_UPDATE: "tenant.appearance.update",
  TENANT_MODULES_READ: "tenant.modules.read",
  TENANT_MODULES_TOGGLE: "tenant.modules.toggle",
  TENANT_ENCRYPTION_ROTATE: "tenant.encryption.rotate",
  TENANT_AUDIT_READ: "tenant.audit.read",
  TENANT_EXPORT_FULL: "tenant.export.full",

  // ── Stores ─────────────────────────────────────────────────────────────
  STORES_READ: "stores.read",
  STORES_CREATE: "stores.create",
  STORES_UPDATE: "stores.update",
  STORES_DELETE: "stores.delete",
  STORES_ASSIGNMENTS_READ: "stores.assignments.read",
  STORES_ASSIGNMENTS_UPDATE: "stores.assignments.update",
  STORES_GEOLOCATION_UPDATE: "stores.geolocation.update",
  STORES_IP_WHITELIST_UPDATE: "stores.ip-whitelist.update",

  // ── Users ──────────────────────────────────────────────────────────────
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_UPDATE_ROLE: "users.update.role",
  USERS_DELETE: "users.delete",
  USERS_PASSWORD_RESET: "users.password.reset",
  USERS_PASSWORD_FORCE_CHANGE: "users.password.force-change",
  USERS_2FA_ENFORCE: "users.2fa.enforce",
  USERS_SESSIONS_REVOKE: "users.sessions.revoke",
  USERS_IMPERSONATE_TENANT: "users.impersonate.tenant",

  // ── Customers ──────────────────────────────────────────────────────────
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_READ_DETAILS: "customers.read.details",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DELETE: "customers.delete",
  CUSTOMERS_CREDIT_ADJUST: "customers.credit.adjust",
  CUSTOMERS_LOYALTY_ADJUST: "customers.loyalty.adjust",
  CUSTOMERS_MERGE: "customers.merge",
  CUSTOMERS_EXPORT: "customers.export",

  // ── Suppliers ──────────────────────────────────────────────────────────
  SUPPLIERS_READ: "suppliers.read",
  SUPPLIERS_CREATE: "suppliers.create",
  SUPPLIERS_UPDATE: "suppliers.update",
  SUPPLIERS_DELETE: "suppliers.delete",
  SUPPLIERS_PAYMENT_RECORD: "suppliers.payment.record",
  SUPPLIERS_EXPORT: "suppliers.export",

  // ── Products ───────────────────────────────────────────────────────────
  PRODUCTS_READ: "products.read",
  PRODUCTS_READ_COST: "products.read.cost",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_VARIANTS_MANAGE: "products.variants.manage",
  PRODUCTS_BATCHES_READ: "products.batches.read",
  PRODUCTS_BATCHES_CREATE: "products.batches.create",
  PRODUCTS_BATCHES_UPDATE: "products.batches.update",
  PRODUCTS_BATCHES_WRITE_OFF: "products.batches.write-off",
  PRODUCTS_SERIALS_READ: "products.serials.read",
  PRODUCTS_SERIALS_MANAGE: "products.serials.manage",
  PRODUCTS_LABELS_PRINT: "products.labels.print",
  PRODUCTS_IMPORT: "products.import",
  PRODUCTS_EXPORT: "products.export",
  CATEGORIES_READ: "categories.read",
  CATEGORIES_MANAGE: "categories.manage",
  BRANDS_READ: "brands.read",
  BRANDS_MANAGE: "brands.manage",
  UNITS_MANAGE: "units.manage",
  LEVIES_READ: "levies.read",
  LEVIES_MANAGE: "levies.manage",

  // ── Inventory ──────────────────────────────────────────────────────────
  INVENTORY_READ: "inventory.read",
  INVENTORY_TRANSFER_CREATE: "inventory.transfer.create",
  INVENTORY_TRANSFER_RECEIVE: "inventory.transfer.receive",
  INVENTORY_TRANSFER_CANCEL: "inventory.transfer.cancel",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_ADJUST_APPROVE: "inventory.adjust.approve",
  INVENTORY_MOVEMENTS_READ: "inventory.movements.read",
  INVENTORY_EXPORT: "inventory.export",

  // ── POS & Sales ────────────────────────────────────────────────────────
  POS_ACCESS: "pos.access",
  POS_DISCOUNT_APPLY: "pos.discount.apply",
  POS_DISCOUNT_BEYOND_LIMIT: "pos.discount.beyond-limit",
  POS_PRICE_OVERRIDE: "pos.price.override",
  POS_CURRENCY_SWITCH: "pos.currency.switch",
  POS_WEIGHT_INPUT: "pos.weight.input",
  SALES_READ: "sales.read",
  SALES_READ_DETAILS: "sales.read.details",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_VOID: "sales.void",
  SALES_VOID_BEYOND_LIMIT: "sales.void.beyond-limit",
  SALES_RETURN_CREATE: "sales.return.create",
  SALES_RETURN_APPROVE: "sales.return.approve",
  SALES_REFUND_CASH: "sales.refund.cash",
  SALES_EXPORT: "sales.export",
  SALES_QUOTATION_READ: "sales.quotation.read",
  SALES_QUOTATION_CREATE: "sales.quotation.create",
  SALES_QUOTATION_UPDATE: "sales.quotation.update",
  SALES_QUOTATION_CONVERT: "sales.quotation.convert",
  CASHIER_SHIFT_OPEN: "cashier-shift.open",
  CASHIER_SHIFT_CLOSE: "cashier-shift.close",
  CASHIER_SHIFT_READ_OWN: "cashier-shift.read.own",
  CASHIER_SHIFT_READ_ALL: "cashier-shift.read.all",
  CASHIER_SHIFT_VARIANCE_OVERRIDE: "cashier-shift.variance.override",

  // ── Purchases ──────────────────────────────────────────────────────────
  PURCHASES_READ: "purchases.read",
  PURCHASES_READ_COST: "purchases.read.cost",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_UPDATE: "purchases.update",
  PURCHASES_RECEIVE: "purchases.receive",
  PURCHASES_CANCEL: "purchases.cancel",
  PURCHASES_EXPORT: "purchases.export",
  PURCHASES_RETURNS_READ: "purchases.returns.read",
  PURCHASES_RETURNS_CREATE: "purchases.returns.create",
  PURCHASES_RETURNS_UPDATE: "purchases.returns.update",
  PURCHASES_RETURNS_DISPATCH: "purchases.returns.dispatch",
  PURCHASES_RETURNS_REFUND_RECORD: "purchases.returns.refund-record",

  // ── Expenses ───────────────────────────────────────────────────────────
  EXPENSES_READ: "expenses.read",
  EXPENSES_READ_ALL: "expenses.read.all",
  EXPENSES_CREATE: "expenses.create",
  EXPENSES_UPDATE: "expenses.update",
  EXPENSES_DELETE: "expenses.delete",
  EXPENSES_APPROVE: "expenses.approve",
  EXPENSES_EXPORT: "expenses.export",
  EXPENSE_CATEGORIES_MANAGE: "expense-categories.manage",

  // ── Currency ───────────────────────────────────────────────────────────
  CURRENCIES_READ: "currencies.read",
  CURRENCIES_ACTIVATE: "currencies.activate",
  EXCHANGE_RATES_READ: "exchange-rates.read",
  EXCHANGE_RATES_CREATE: "exchange-rates.create",
  EXCHANGE_RATES_REFRESH_FROM_API: "exchange-rates.refresh.from-api",

  // ── Reports ────────────────────────────────────────────────────────────
  REPORTS_SALES_READ: "reports.sales.read",
  REPORTS_PROFIT_READ: "reports.profit.read",
  REPORTS_STOCK_READ: "reports.stock.read",
  REPORTS_PURCHASES_READ: "reports.purchases.read",
  REPORTS_EXPENSES_READ: "reports.expenses.read",
  REPORTS_CASHIER_READ: "reports.cashier.read",
  REPORTS_CUSTOMER_READ: "reports.customer.read",
  REPORTS_TAX_READ: "reports.tax.read",
  REPORTS_HR_ATTENDANCE_READ: "reports.hr.attendance.read",
  REPORTS_HR_PAYROLL_READ: "reports.hr.payroll.read",
  REPORTS_EXPORT: "reports.export",
  REPORTS_SCHEDULED_READ: "reports.scheduled.read",
  REPORTS_SCHEDULED_CREATE: "reports.scheduled.create",
  REPORTS_SCHEDULED_UPDATE: "reports.scheduled.update",
  REPORTS_SCHEDULED_DELETE: "reports.scheduled.delete",

  // ── Receipts ───────────────────────────────────────────────────────────
  RECEIPTS_TEMPLATE_READ: "receipts.template.read",
  RECEIPTS_TEMPLATE_UPDATE: "receipts.template.update",
  RECEIPTS_REPRINT: "receipts.reprint",
  RECEIPTS_SEND_EMAIL: "receipts.send.email",
  RECEIPTS_SEND_SMS: "receipts.send.sms",
  RECEIPTS_SEND_WHATSAPP: "receipts.send.whatsapp",
  RECEIPTS_THERMAL_PRINT: "receipts.thermal.print",

  // ── HR: Employees ─────────────────────────────────────────────────────
  HR_EMPLOYEES_READ: "hr.employees.read",
  HR_EMPLOYEES_READ_SENSITIVE: "hr.employees.read.sensitive",
  HR_EMPLOYEES_READ_SALARY: "hr.employees.read.salary",
  HR_EMPLOYEES_CREATE: "hr.employees.create",
  HR_EMPLOYEES_UPDATE: "hr.employees.update",
  HR_EMPLOYEES_UPDATE_SENSITIVE: "hr.employees.update.sensitive",
  HR_EMPLOYEES_UPDATE_SALARY: "hr.employees.update.salary",
  HR_EMPLOYEES_TERMINATE: "hr.employees.terminate",
  HR_EMPLOYEES_DOCUMENTS_READ: "hr.employees.documents.read",
  HR_EMPLOYEES_DOCUMENTS_UPLOAD: "hr.employees.documents.upload",
  HR_EMPLOYEES_DOCUMENTS_DELETE: "hr.employees.documents.delete",
  HR_EMPLOYEES_EXPORT: "hr.employees.export",
  HR_DEPARTMENTS_READ: "hr.departments.read",
  HR_DEPARTMENTS_MANAGE: "hr.departments.manage",
  HR_DESIGNATIONS_READ: "hr.designations.read",
  HR_DESIGNATIONS_MANAGE: "hr.designations.manage",
  HR_CONTRACTS_READ: "hr.contracts.read",
  HR_CONTRACTS_CREATE: "hr.contracts.create",
  HR_CONTRACTS_UPDATE: "hr.contracts.update",

  // ── HR: Attendance & Shifts ───────────────────────────────────────────
  HR_ATTENDANCE_READ_OWN: "hr.attendance.read.own",
  HR_ATTENDANCE_READ_TEAM: "hr.attendance.read.team",
  HR_ATTENDANCE_READ_ALL: "hr.attendance.read.all",
  HR_ATTENDANCE_CHECK_IN_MANUAL: "hr.attendance.check-in.manual",
  HR_ATTENDANCE_CHECK_OUT_MANUAL: "hr.attendance.check-out.manual",
  HR_ATTENDANCE_REGULARIZE_REQUEST: "hr.attendance.regularize.request",
  HR_ATTENDANCE_REGULARIZE_APPROVE: "hr.attendance.regularize.approve",
  HR_ATTENDANCE_REGULARIZE_REJECT: "hr.attendance.regularize.reject",
  HR_ATTENDANCE_BIOMETRIC_READ: "hr.attendance.biometric.read",
  HR_ATTENDANCE_BIOMETRIC_CONFIGURE: "hr.attendance.biometric.configure",
  HR_ATTENDANCE_EXPORT: "hr.attendance.export",
  HR_SHIFTS_READ: "hr.shifts.read",
  HR_SHIFTS_TEMPLATE_MANAGE: "hr.shifts.template.manage",
  HR_SHIFTS_SCHEDULE_READ: "hr.shifts.schedule.read",
  HR_SHIFTS_SCHEDULE_CREATE: "hr.shifts.schedule.create",
  HR_SHIFTS_SCHEDULE_UPDATE: "hr.shifts.schedule.update",
  HR_SHIFTS_SCHEDULE_DELETE: "hr.shifts.schedule.delete",
  HR_SHIFTS_SWAP_REQUEST_OWN: "hr.shifts.swap.request.own",
  HR_SHIFTS_SWAP_RESPOND: "hr.shifts.swap.respond",
  HR_SHIFTS_SWAP_APPROVE: "hr.shifts.swap.approve",

  // ── HR: Leave & Holiday ───────────────────────────────────────────────
  HR_LEAVE_TYPES_READ: "hr.leave.types.read",
  HR_LEAVE_TYPES_MANAGE: "hr.leave.types.manage",
  HR_LEAVE_POLICIES_READ: "hr.leave.policies.read",
  HR_LEAVE_POLICIES_MANAGE: "hr.leave.policies.manage",
  HR_LEAVE_BALANCES_READ_OWN: "hr.leave.balances.read.own",
  HR_LEAVE_BALANCES_READ_TEAM: "hr.leave.balances.read.team",
  HR_LEAVE_BALANCES_READ_ALL: "hr.leave.balances.read.all",
  HR_LEAVE_BALANCES_ADJUST: "hr.leave.balances.adjust",
  HR_LEAVE_REQUEST_CREATE_OWN: "hr.leave.request.create.own",
  HR_LEAVE_REQUEST_CREATE_FOR: "hr.leave.request.create.for",
  HR_LEAVE_REQUEST_READ_OWN: "hr.leave.request.read.own",
  HR_LEAVE_REQUEST_READ_TEAM: "hr.leave.request.read.team",
  HR_LEAVE_REQUEST_READ_ALL: "hr.leave.request.read.all",
  HR_LEAVE_REQUEST_CANCEL_OWN: "hr.leave.request.cancel.own",
  HR_LEAVE_REQUEST_APPROVE: "hr.leave.request.approve",
  HR_LEAVE_REQUEST_REJECT: "hr.leave.request.reject",
  HR_HOLIDAYS_READ: "hr.holidays.read",
  HR_HOLIDAYS_MANAGE: "hr.holidays.manage",

  // ── HR: Payroll ───────────────────────────────────────────────────────
  HR_PAYROLL_READ: "hr.payroll.read",
  HR_PAYROLL_READ_PAYSLIP_ALL: "hr.payroll.read.payslip.all",
  HR_PAYROLL_SALARY_STRUCTURE_READ: "hr.payroll.salary-structure.read",
  HR_PAYROLL_SALARY_STRUCTURE_MANAGE: "hr.payroll.salary-structure.manage",
  HR_PAYROLL_SALARY_COMPONENT_STATUTORY_OVERRIDE: "hr.payroll.salary-component.statutory.override",
  HR_PAYROLL_COUNTRY_PRESET_READ: "hr.payroll.country-preset.read",
  HR_PAYROLL_COUNTRY_PRESET_APPLY: "hr.payroll.country-preset.apply",
  HR_PAYROLL_RUN_CREATE: "hr.payroll.run.create",
  HR_PAYROLL_RUN_PROCESS: "hr.payroll.run.process",
  HR_PAYROLL_RUN_APPROVE: "hr.payroll.run.approve",
  HR_PAYROLL_RUN_DISBURSE: "hr.payroll.run.disburse",
  HR_PAYROLL_RUN_CANCEL: "hr.payroll.run.cancel",
  HR_PAYROLL_PAYSLIP_VOID: "hr.payroll.payslip.void",
  HR_PAYROLL_PAYSLIP_REGENERATE_PDF: "hr.payroll.payslip.regenerate-pdf",
  HR_PAYROLL_ADVANCE_READ: "hr.payroll.advance.read",
  HR_PAYROLL_ADVANCE_CREATE: "hr.payroll.advance.create",
  HR_PAYROLL_ADVANCE_APPROVE: "hr.payroll.advance.approve",
  HR_PAYROLL_ADVANCE_DISBURSE: "hr.payroll.advance.disburse",
  HR_PAYROLL_EXPORT: "hr.payroll.export",

  // ── ESS (Employee Self-Service) ──────────────────────────────────────
  ESS_PROFILE_READ: "ess.profile.read",
  ESS_PROFILE_UPDATE: "ess.profile.update",
  ESS_ATTENDANCE_READ: "ess.attendance.read",
  ESS_ATTENDANCE_CHECK_IN: "ess.attendance.check-in",
  ESS_ATTENDANCE_CHECK_OUT: "ess.attendance.check-out",
  ESS_ATTENDANCE_REGULARIZE: "ess.attendance.regularize",
  ESS_SHIFTS_READ: "ess.shifts.read",
  ESS_SHIFTS_SWAP_REQUEST: "ess.shifts.swap.request",
  ESS_SHIFTS_SWAP_RESPOND: "ess.shifts.swap.respond",
  ESS_LEAVE_TYPES_READ: "ess.leave.types.read",
  ESS_LEAVE_BALANCE_READ: "ess.leave.balance.read",
  ESS_LEAVE_REQUEST_CREATE: "ess.leave.request.create",
  ESS_LEAVE_REQUEST_READ: "ess.leave.request.read",
  ESS_LEAVE_REQUEST_CANCEL: "ess.leave.request.cancel",
  ESS_PAYSLIPS_READ: "ess.payslips.read",
  ESS_PAYSLIPS_DOWNLOAD: "ess.payslips.download",
  ESS_HOLIDAYS_READ: "ess.holidays.read",
  ESS_DOCUMENTS_READ: "ess.documents.read",

  // ── AI Insights ───────────────────────────────────────────────────────
  AI_INSIGHTS_QUERY: "ai.insights.query",
  AI_INSIGHTS_READ_HISTORY_OWN: "ai.insights.read.history.own",
  AI_INSIGHTS_READ_HISTORY_ALL: "ai.insights.read.history.all",
  AI_INSIGHTS_CONFIG_READ: "ai.insights.config.read",
  AI_INSIGHTS_CONFIG_UPDATE: "ai.insights.config.update",

  // ── Notifications ─────────────────────────────────────────────────────
  NOTIFICATIONS_TEMPLATES_READ: "notifications.templates.read",
  NOTIFICATIONS_TEMPLATES_UPDATE: "notifications.templates.update",
  NOTIFICATIONS_TEMPLATES_CREATE: "notifications.templates.create",
  NOTIFICATIONS_TEMPLATES_DELETE: "notifications.templates.delete",
  NOTIFICATIONS_SEND_MANUAL: "notifications.send.manual",
  NOTIFICATIONS_LOG_READ: "notifications.log.read",
  NOTIFICATIONS_CONFIG_PROVIDERS: "notifications.config.providers",

  // ── Webhooks ──────────────────────────────────────────────────────────
  WEBHOOKS_READ: "webhooks.read",
  WEBHOOKS_CREATE: "webhooks.create",
  WEBHOOKS_UPDATE: "webhooks.update",
  WEBHOOKS_DELETE: "webhooks.delete",
  WEBHOOKS_TEST: "webhooks.test",
  WEBHOOKS_DELIVERIES_READ: "webhooks.deliveries.read",
  WEBHOOKS_DELIVERIES_RETRY: "webhooks.deliveries.retry",
  WEBHOOKS_CIRCUIT_RESET: "webhooks.circuit.reset",

  // ── Subscription Billing ──────────────────────────────────────────────
  BILLING_SUBSCRIPTIONS_READ_OWN: "billing.subscriptions.read.own",
  BILLING_SUBSCRIPTIONS_UPGRADE: "billing.subscriptions.upgrade",
  BILLING_SUBSCRIPTIONS_DOWNGRADE: "billing.subscriptions.downgrade",
  BILLING_SUBSCRIPTIONS_CANCEL: "billing.subscriptions.cancel",
  BILLING_INVOICES_READ_OWN: "billing.invoices.read.own",
  BILLING_PAYMENT_METHOD_UPDATE: "billing.payment-method.update",
  BILLING_PLANS_READ: "billing.plans.read",
  BILLING_PLANS_MANAGE: "billing.plans.manage",
  BILLING_SUBSCRIPTIONS_READ_ALL: "billing.subscriptions.read.all",

  // ── KDS / Customer Display / Integrations ─────────────────────────────
  KDS_ACCESS: "kds.access",
  KDS_ORDERS_READ: "kds.orders.read",
  KDS_ORDERS_ACKNOWLEDGE: "kds.orders.acknowledge",
  KDS_ORDERS_PREPARING: "kds.orders.preparing",
  KDS_ORDERS_READY: "kds.orders.ready",
  KDS_ORDERS_SERVED: "kds.orders.served",
  KDS_ORDERS_CANCEL: "kds.orders.cancel",
  KDS_STATIONS_MANAGE: "kds.stations.manage",
  CUSTOMER_DISPLAY_ACCESS: "customer-display.access",
  CUSTOMER_DISPLAY_SESSION_READ: "customer-display.session.read",
  CUSTOMER_DISPLAY_SESSION_MANAGE: "customer-display.session.manage",
  INTEGRATIONS_READ: "integrations.read",
  INTEGRATIONS_CREATE: "integrations.create",
  INTEGRATIONS_UPDATE: "integrations.update",
  INTEGRATIONS_DISCONNECT: "integrations.disconnect",
  INTEGRATIONS_SYNC_TRIGGER: "integrations.sync.trigger",
  INTEGRATIONS_SYNC_HISTORY_READ: "integrations.sync.history.read",
} as const;

export type PermissionV2 = (typeof PERMISSIONS_V2)[keyof typeof PERMISSIONS_V2];

export function hasV2Permission(
  permissions: string[] | undefined,
  perm: PermissionV2 | string,
): boolean {
  if (!permissions) return false;
  return permissions.includes(perm);
}

export function hasAnyV2Permission(
  permissions: string[] | undefined,
  perms: Array<PermissionV2 | string>,
): boolean {
  if (!permissions) return false;
  return perms.some((p) => permissions.includes(p));
}

export function hasAllV2Permissions(
  permissions: string[] | undefined,
  perms: Array<PermissionV2 | string>,
): boolean {
  if (!permissions) return false;
  return perms.every((p) => permissions.includes(p));
}
